# IRC
nick = "oodle-dev"
name = "oodle-dev"
user = "oodle-dev"
sasl_user = ""
sasl_pass = ""
server = "chat.freenode.net"
port = 6667
channel = "##oodle-test"
# Retry if connection drops; has exp. backoff
retry = true
# Where to store sqlite file
dbpath = "store.sqlite"
# Webhook
secret = "7570abf6d5619dd0f9668551845ffe02a082fddf4a097306dae9b05ad6a2" # OFC change this
webhook_addr = "127.0.0.1:8000"
commands = [
    "seen",
    "tell",
    "rep",
    "give",
    "rank",
    "echo",
    "title",
    "hackterm"
]
points = [1,2,-1]
cooldowns = ["20s", "8m", "10s"]
registered_only = true
# .site -> https://pacn.in etc.
[custom_commands]
".site" = "https://pacn.in"
".google" = "https://google.in"