# IRC
nick = "oodle-devvvv"
name = "oodle-dev"
user = "oodle-dev"
sasl_user = ""
sasl_pass = ""
server = "chat.freenode.net"
port = 6667
channel = "##oodle-test"
# Retry if connection drops; has exp. backoff
retry = true
# Where to store sqlite file
dbpath = "store.toml"